# Generated by Django 4.1.4 on 2023-02-05 16:42

import django.core.exceptions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.exceptions.ValidationError]),
        ),
    ]
